export { default as updateNumber } from './update-number'
export { default as updateScroll } from './update-scroll'
export { default as updateUnit } from './update-unit'
export { default as updateObject } from './update-object'
export { default as updateStyles } from './update-styles'
