export { default as animate } from './animate'
export { default as core } from './core'
export { default as number } from './number'
export { default as object } from './object'
export { default as scroll } from './scroll'
export { default as styles } from './styles'
export * from './timing'
export { default as unit } from './unit'
export { default as updateObject } from './update-object'
export { version } from '../package.json'
export { default as withEase } from './with-ease'
